name: Update Quote

on:
  workflow_dispatch:  
  schedule:
    - cron: '30 6 * * *'  # Corre todos los días a las 6:30 AM UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Update Quote
        run: node update-quote.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git pull origin main --rebase
          git add .
          git -c user.name='Devmike117' -c user.email='mikealesso768@gmail.com' commit -m "Update README with daily quote"
          git push

